### DISCUSSION TITLE
Formal multi-dictionary and cross-lingual support are ready for public testing

### DISCUSSION THREAD

**Discussion by yqzhishen** [openvpi/DiffSinger#203] [Announcements]
We have already seen many multi-lingual voicebanks in the community. Most of them use separated phoneme tags with caps, suffixes or numbers to avoid conflicts, leaving chaos in labels and user experience. It should be great if we can formally support combining different dictionaries and languages in a graceful way. With the new feature in this repository, you can use the most understandable and commonly accepted labels for each language. We hope this can unify the ecosystem of DiffSinger labeling and voicebank making.

**The new feature will be temporarily kept on the `multi-dict` branch. Please note that the following things are under development and testing, and may change (or even break) before they are merged into the main branch.**

### Language-specific phonemes

If there are multiple dictionaries (languages), all language-specific phonemes will be prefixed with its language name. For example: `zh/a`, `ja/o`, `en/eh`. This step is done automatically by the binarizer, and you do not need to distinguish the phonemes from different languages by yourself anymore. **As a cost, the slash `/` becomes a reserved character and should not be used in phoneme names.**

**We highly recommend using ISO 639 language codes as language tags.** For example, `zh` and `zho` stands for Chinese (`cmn` specifically for Mandarin Chinese), `ja` and `jpn` for Japanese, `en` and `eng` for English, `yue` for Cantonese (Yue). You can download a complete language code table from https://iso639-3.sil.org/code_tables/download_tables.

### Global phonemes

Some phonemes do not belong to any language, including reserved tags (`AP` and `SP`), and other user-defined tags (`EP`, `VF`, `Edge`, `GlottalStop`, etc.). These tags will not be prefixed with language, and are prior when identificating phoneme names. **Language-specific phonemes should not have same names with global phonemes; otherwise they will be regarded as global phonemes.**

### Phoneme identification

There are two ways to identify a phoneme:

1. With the full name. For example, `zh/a` for the phoneme `a` of the Chinese language, `AP` for the global phoneme of breath.
2. With a language context and the short name. For example, in a context defined as Chinese language (`zh`), `a` actually equals `zh/a`, while `AP` is still `AP` (global phonemes are prior).

### Phoneme merging and language embedding

The phoneme set expands rapidly with the number of languages. There are actually many similar phonemes that can be merged. However, different people may have different ideas about phoneme merging, and it is very inconvenient to adjust the labels. For this reason, we now support flexible phoneme merging groups that everyone can define without pain. For example, if we merged the three phonemes `zh/i`, `ja/i` and `en/iy`, they all still have their names, but they will be mapped to the same phoneme ID before sending into the model. Global phonemes are never merged.

Directly merging some phonemes is probably one step too far. Previous experiments have shown some accent leaks after doing this. To solve this issue, we implemented language embedding to distinguish the same phoneme in different languages. All cross-lingual phonemes (where phonemes from two or more languages are merged together) will be tagged with its actual language, but all cross-lingual phonemes from one language share the same embedding vector. In this way, the merged phonemes are closer to (but not completely the same with) each other.

Internal experiments have shown that merging phonemes and language embedding can help reducing timbre and accent leaks in cross-lingual (out-of-domain) singing compared to baseline.

## Dictionaries

Dictionary format is not changed, except that you may rename your phonemes to cancel the tricks to avoid phoneme name conflicts. Global phonemes can also appear in the dictionary; all other phonemes will be treated as language-specific phonemes.

## Datasets and labels

Each dataset should have a main language. If you have many recordings in multiple languages, it is recommended to separate them by language (you can merge their speaker IDs afterwards). In each dataset, the main language is set as the language context, and phoneme labels in transcriptions.csv do not need a prefix (short name). It is also valid if there are phonemes from other languages, but all of them should be prefixed with their actual language (full name). Global phonemes should not be prefixed in any datasets.

## Configuration

Below is an example configuration for multi-dictionary models:

```yaml
dictionaries:  # define all language tags and their corresponding dictionary
  zh: dictionaries/opencpop-extension.txt
  ja: dictionaries/japanese_dict_full.txt
  en: dictionaries/ds_cmudict-07b.txt
extra_phonemes: []  # user-defined global phonemes + addictional language-specific phonemes (full name should be used)
merged_phoneme_groups:  # define all phoneme merging groups; global phonemes should not appear here
  - [zh/i, ja/i, en/iy]
  - [zh/s, ja/s, en/s]
  # ... (other groups omitted for brevity)

datasets:  # define all raw datasets
  - raw_data_dir: data/xxx1/raw  # path of the dataset (equivalent to former raw_data_dir)
    speaker: speaker1  # speaker name (equivalent to former speakers)
    spk_id: 0  # optional; use this to merge two datasets; otherwise automatically assigned
    language: zh  # language tag (main language) of this dataset
    test_prefixes:  # optional; validation samples from this dataset
      - wav1
      - wav2
  - raw_data_dir: data/xxx2/raw
    speaker: speaker2
    spk_id: 1
    language: ja
    test_prefixes:
      - wav1
      - wav2
  # ... (other datasets omitted for brevity)

use_lang_id: true  # whether to use language embedding; only take effects if there are cross-lingual phonemes
num_lang: 3  # number of languages; should be >= number of defined languages
```

## Preprocessing, training and inference

In preprocessing, you only need to cover all phoneme IDs instead of all phoneme names to pass the coverage checks.

The training API is completely the same as before.

The inference API has a new option `--lang` for multi-lingual models. This is used to define the language context for all the input segments. Without the option, a `lang` key in each segment can also define the language context. Rules for phoneme name sequence is the same as dataset transcription.

## Deployment

The ONNX exporters have been adapted to multi-lingual models. The only difference in ONNX is that models with language embedding accepts a new `languages` input besides `tokens`. Meanwhile, the language and phoneme mapping (name->ID) are now given by JSON files instead of a line-by-line `phonemes.txt`.

OpenUTAU does not support this new feature currently. We will keep contact with its developers on how to implement multi-lingual support for a pleasant user experience.

---

Questions? Feedbacks? Thoughts? Experimental results? Dictionary proposals? Please leave comments below and discuss with people in the community.
