### ISSUE TITLE
关于breathiness的控制问题

### ISSUE THREAD

**Issue by mindrover** [openvpi/DiffSinger#161]
哈喽~ @yqzhishen 
我使用\~2.5h的单人女声数据集（数据增强后\~6h）训练了acoustic model（以及variance model）。直接合成时基本正常，
但发现在调整breathiness曲线后合成结果出现了一些问题。

直接合成结果：
[test_Track1.zip](https://github.com/openvpi/DiffSinger/files/13985975/test_Track1.zip)

对breathiness曲线尝试进行简单调整后的结果：
[test_Track2.zip](https://github.com/openvpi/DiffSinger/files/13985990/test_Track2.zip)

调整后breathiness曲线：
![716a6ba889597f75c832032b1e2c589](https://github.com/openvpi/DiffSinger/assets/128977016/8d8c23af-29ee-4261-9600-e380567b47b7)

感觉breathiness调低之后输出结果跟预期效果有出入，咬字发音受到了一些影响。按理说，对气声参数的控制好像不应该是这个效果……
我也尝试了[DiffSinger自制声库分享列表](https://docs.qq.com/sheet/DQXNDY0pPaEpOc3JN?tab=BB08J2)中**挚彬Club**发布的**挚彬·时羽**声库，感觉那个声库的效果是符合预期的。

想请问下，对于这种情况，有任何可考虑的建议吗？多谢了~

额外的信息，训练所用配置如下：
```
use_energy_embed: true
use_breathiness_embed: true
use_key_shift_embed: true
use_speed_embed: true

augmentation_args:
  random_pitch_shifting:
    enabled: true
    range: [-5., 5.]
    scale: 0.75
  fixed_pitch_shifting:
    enabled: false
    targets: [-5., 5.]
    scale: 0.5
  random_time_stretching:
    enabled: true
    range: [0.5, 2.]
    domain: log  # or linear
    scale: 0.75

residual_channels: 512
residual_layers: 20

# shallow diffusion
use_shallow_diffusion: true
K_step: 400
K_step_infer: 400
shallow_diffusion_args:
  train_aux_decoder: true
  train_diffusion: true
  val_gt_start: false
  aux_decoder_arch: convnext
  aux_decoder_args:
    num_channels: 512
    num_layers: 6
    kernel_size: 7
    dropout_rate: 0.1
  aux_decoder_grad: 0.1
lambda_aux_mel_loss: 0.2
```
